### ISSUE TITLE
Insert Screenshot fails

### ISSUE THREAD

**Issue by MurrayVK3** [jaap-karssenberg/zim-desktop-wiki#134]
Version 0.67 RC2 on Linux Mint 17

Insert screen shot with either scrot or import I'm getting:

INFO: Spawning: ['import', '-silent', '-window', 'root', '/tmp/zim-murray/insert-screenshot.png'] (cwd: None)
INFO: Rename /tmp/zim-murray/insert-screenshot.png to /media/localHDD/MurraysPersonalStuff/Dropbox/Zim/zz/screenshot_2017-06-24-154843.png
INFO: Remove file: /tmp/zim-murray/insert-screenshot.png
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/applications.py", line 290, in <lambda>
    lambda pid, status, data: callback(status, data), data)
  File "/usr/lib/python2.7/dist-packages/zim/plugins/screenshot.py", line 215, in callback
    pageview.insert_image(imgfile, interactive=False, force=True)
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/pageview.py", line 5982, in insert_image
    assert isinstance(file, File)
AssertionError

Many thanks
Murray

**Comment by MurrayVK3** [comment]
Commenting out the assert test fixes the assert error (naturally!).   Screen insert then seems to work as expected.    The assert tests isinstance(file,File) where file seems to be simply a string of the path to the image file, not an actual instance of a File class.  Perhaps the test is wrong?  I'm not sure, Python isn't my native language.

Murray
