### ISSUE TITLE
0.66 crashed when moved a TODO entry to a parent page

### ISSUE THREAD

**Issue by cheese** [jaap-karssenberg/zim-desktop-wiki#18]
But not simply reproducible.

Zim 0.66 on Fedora 24.

__init__.py:728:open_page:AssertionError: Could not close page

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zim/gui/pageindex.py", line 404, in do_page_activated
    self.ui.open_page(path)
  File "/usr/lib/python2.7/site-packages/zim/actions.py", line 132, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zim/gui/__init__.py", line 728, in open_page
    raise AssertionError, 'Could not close page'
AssertionError: Could not close page

Local variables in innermost frame:
path: <PageIndexRecord: XX:6.2TODO:USB直通>
self: <GtkInterface object at 0x7f427ffbee10 (zim+gui+GtkInterface at 0x55d8a2b394e0)>
page: <Page: XX:6.2TODO:USB直通>

**Comment by jaap-karssenberg** [comment]
What do you mean by "crashed" - did this cause the application to exit ? If so was it a segfault or not ?

**Comment by cheese** [comment]
The program did not exit. Just throw a back trace under the hood.

**Comment by jaap-karssenberg** [comment]
This means that zim failed to save the current file, maybe the file write failed, error log should provide more error output to indicate root cause.
