### ISSUE TITLE
Fix corner case in zim newfs

### ISSUE THREAD

**Issue by mexicarne** [jaap-karssenberg/zim-desktop-wiki#23]
Hello, there is some code missing in `zim/newfs/__init__.py`. It is triggered when user have locale not set. There is no logger object created, so it will fail with 
```python
No handlers could be found for logger "zim.fs"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 25, in <module>
    import makeman # helper script
  File "makeman.py", line 14, in <module>
    from zim.main import HelpCommand
  File "zim/main/__init__.py", line 28, in <module>
    from zim.notebook import Notebook, Path, \
  File "zim/notebook/__init__.py", line 39, in <module>
    from .info import NotebookInfo, NotebookInfoList, \
  File "zim/notebook/info.py", line 19, in <module>
    from .notebook import NotebookConfig, _resolve_relative_config
  File "zim/notebook/notebook.py", line 22, in <module>
    from zim.newfs import LocalFolder
  File "zim/newfs/__init__.py", line 19, in <module>
    logger.warn('Filesystem encoding is set to ASCII or Latin1, using UTF-8 instead')
NameError: name 'logger' is not defined
```

Here is the [patch](https://svnweb.freebsd.org/ports/head/deskutils/zim/files/patch-zim_newfs_____init____.py?view=markup&pathrev=440457) we applied locally:

Also this is the only file with windows-style line endings. Would you please fix it too to make it consistent with overall code? Thank you.

**Comment by jaap-karssenberg** [comment]
Will be fixes in c951d49
