### ISSUE TITLE
Gtk3: AttributeError: 'WindowsFile' object has no attribute '_recover'

### ISSUE THREAD

**Issue by aprotoss** [jaap-karssenberg/zim-desktop-wiki#344]
I try to use "next" branch in Mingw-w64 32bit (Msys2) on Windows,
there is a error message:
```
$ python3 zim.py
Traceback (most recent call last):
  File "zim.py", line 39, in <module>
    import zim
  File "D:\msys32\home\Jacky Zhang\zim\zim-desktop-wiki\zim\__init__.py", line 195, in <module>
    import zim.config
  File "D:\msys32\home\Jacky Zhang\zim\zim-desktop-wiki\zim\config\__init__.py", line 9, in <module>
    from .basedirs import *
  File "D:\msys32\home\Jacky Zhang\zim\zim-desktop-wiki\zim\config\basedirs.py", line 88, in <module>
    set_basedirs()
  File "D:\msys32\home\Jacky Zhang\zim\zim-desktop-wiki\zim\config\basedirs.py", line 49, in set_basedirs
    zim_data_dir = File(zim.ZIM_EXECUTABLE).dir.subdir('data')
  File "D:\msys32\home\Jacky Zhang\zim\zim-desktop-wiki\zim\fs.py", line 1382, in __init__
    self._recover() # just to be sure
AttributeError: 'WindowsFile' object has no attribute '_recover'

```
And, i try to fixed it, please reference the attachment.

[windowsfile_no_attribute.patch.txt](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1746569/windowsfile_no_attribute.patch.txt)

**Comment by jaap-karssenberg** [comment]
Yes, removing this line should be fine. But trigger for me to do another
code review of this class and check if there are more loose bits of the
change that left this.

-- Jaap
