### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by banan314** [jaap-karssenberg/zim-desktop-wiki#406]
After I run 
```
./zim.py
```
I get the error message:
```
Traceback (most recent call last):
  File "./setup.py", line 22, in <module>
    from zim import __version__, __url__
  File "zim-desktop-wiki/zim/__init__.py", line 184, in <module>
    import zim.environ # initializes environment parameters
  File "zim-desktop-wiki/zim/environ.py", line 16, in <module>
    from zim.fs import ENCODING, isdir
  File "zim-desktop-wiki/zim/fs.py", line 165, in <module>
    import xdg.Mime as xdgmime
  File "/usr/local/lib/python2.7/dist-packages/xdg.py", line 18
SyntaxError: Non-ASCII character '\xc2' in file /usr/local/lib/python2.7/dist-packages/xdg.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
This is the line 18 from `/usr/local/lib/python2.7/dist-packages/xdg.py`:
```
# Copyright © 2016-2018 Scott Stevenson <scott@stevenson.io>
```
After I deleted the character :copyright:, the following error occured:
```
  File "/usr/local/lib/python2.7/dist-packages/xdg.py", line 40
    def _getenv(variable: str, default: str) -> str:
                        ^
SyntaxError: invalid syntax
```
I replaced the line 40 with the following:
```
def _getenv(variable, default):
```
And it kind of worked, but I got the same warning as in the issue #199.

**Comment by genodeftest** [comment]
The second issue is clearly a bug in your distribution of the `xdg` python module. This syntax has been introduced in a recent python version (3.6 I think) and must not be placed in any python file below `/usr/local/lib/python2.7/` or `/usr/lib/python2.7`. How did you get that package there? Either the method putting it there or the source is broken. This is not a bug in Zim.

[Upstream](https://pypi.python.org/pypi/xdg/3.0.2) claims they only support Python 3.6, so it isn't their fault either.

The first issue with the © character is probably caused by the same mistake as that character is allowed in python 3 source files but not in python 2.
