### ISSUE TITLE
Zim (0.68) failing to record opened pages on MacOS High Sierra

### ISSUE THREAD

**Issue by reagle** [jaap-karssenberg/zim-desktop-wiki#434]
As [discussed on the list](https://lists.launchpad.net/zim-wiki/msg04682.html), my pathbar no longer works.

The problem began in that the page zim started with was not the home page, nor the last page I was on. This problem is deeper than I expected and has to do with the state/cache: on_close_page ... self.save_uistate(). Here is my `notebook.zim`:

```
[Notebook]
disable_trash=False
document_root=
endofline=unix
home=Home
icon=
interwiki=jp
name=plan
profile=
shared=False
```

Whether shared is True or False, it keeps state in `$HOME/.cache` directory:

```
DEBUG: Running from a source dir: /Users/reagle/bin/zim-0.68
DEBUG: Set XDG_DATA_HOME to /Users/reagle/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share>, <Dir: /usr/local/share>]
DEBUG: Set XDG_CONFIG_HOME to /Users/reagle/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /Users/reagle/.cache
```

There, I deleted `notebook-Users_reagle_joseph_plan_zim/`. And hurray, I now start on the home page, but still the path state is never retained. After I browse a bunch of pages and quit, the state is:

```
[History]
list=[["Home",0,null]]
recent=[["Home",0,null]]
current=0
```

Also (and I suspect this is the crux) as I browse the pages I get these errors:

```
DEBUG: BackgroundCheck finished
Traceback (most recent call last):
  File "/Users/reagle/bin/zim-0.68/zim/gui/__init__.py", line 2411, in on_close_page
    self.save_uistate()
  File "/Users/reagle/bin/zim-0.68/zim/gui/__init__.py", line 2363, in save_uistate
    self.uistate['windowpos'] = self.get_position()
  File "/Users/reagle/bin/zim-0.68/zim/config/dicts.py", line 549, in __setitem__
    raise KeyError('Config key "%s" has not been defined' % k)
KeyError: 'Config key "windowpos" has not been defined'
INFO: Open page: Misc:Housing (Misc:Housing)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
Traceback (most recent call last):
  File "/Users/reagle/bin/zim-0.68/zim/gui/__init__.py", line 2411, in on_close_page
    self.save_uistate()
  File "/Users/reagle/bin/zim-0.68/zim/gui/__init__.py", line 2363, in save_uistate
    self.uistate['windowpos'] = self.get_position()
  File "/Users/reagle/bin/zim-0.68/zim/config/dicts.py", line 549, in __setitem__
    raise KeyError('Config key "%s" has not been defined' % k)
KeyError: 'Config key "windowpos" has not been defined'
INFO: Open page: Misc:Finance (Misc:Finance)
```

**Comment by reagle** [comment]
Six months now, any help?

**Comment by reagle** [comment]
I've had the issue recur on one of my machines. I've deleted the cache and zim isn't able to remember path history.

**Comment by reagle** [comment]
Thanks. Because I can't use the gtk3+ version because of #590, can I apply this to zim 0.69? In that version, there is no `mainwindow.py`so I'm not sure where I would apply it.

**Comment by reagle** [comment]
Might this fix #589 as well? That bug also complains of `windowpos`not being defined.

**Comment by jaap-karssenberg** [comment]
I've had a look at patching this for the python2-gtk2 branch, but afraid it ain't as straight forward as in the gtk3 branch. Reason is that the initialization is more complex. Simplifications I did in the gtk3 branch help to solve this more easily.

**Comment by reagle** [comment]
With #434 and #589 fixed, I'd happily abandon python2-gtk2 except that #590 prevents copying-and-pasting in the gtk+3 version.

**Comment by jaap-karssenberg** [comment]
I understand, but 590 is not in my power to solve I'm afraid.
