### ISSUE TITLE
gtk3: error when trying to open Task List

### ISSUE THREAD

**Issue by raztus** [jaap-karssenberg/zim-desktop-wiki#529]
Environment:
- Python 3.7.0
- gtk3 3.22.30-1
- python-gobject 3.28.3-2
- Arch Linux
- Running zim/next (7cf2513ca)

Enabled Task List plugin. Opened a brand new notebook (or an existing one). Clicked the Task List button in the toolbar. Got this error:

```
This is zim 0.68-gtk3
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 7, 0, 'final', 0)
PyGObject: (3, 28, 3)
No bzr version-info found

======= Traceback =======
  File "/home/user/project/zim-desktop-wiki/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/home/user/project/zim-desktop-wiki/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/user/project/zim-desktop-wiki/zim/plugins/tasklist/__init__.py", line 151, in show_task_list
    dialog = TaskListDialog.unique(self, self.pageview, tasksview, self.plugin.preferences)
  File "/home/user/project/zim-desktop-wiki/zim/gui/widgets.py", line 2724, in unique
    dialog = klass(*args, **opts)
  File "/home/user/project/zim-desktop-wiki/zim/plugins/tasklist/gui.py", line 184, in __init__
    nb_ext = find_extension(self.pageview.notebook, TaskListNotebookExtension)
AttributeError: 'TaskListDialog' object has no attribute 'pageview'
```

**Comment by raztus** [comment]
Worth noting that on a fresh clone and checkout of branch 'next' many tests fail. I won't submit a bug for this until I've poked around at the tests more. Please let me know if there's something I should have done before running test.py.

```
FAIL: runTest (tests.main.TestIPC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/project/zim-desktop-wiki/tests/main.py", line 203, in runTest
    "name too long: %s" % os.path.basename(SERVER_ADDRESS)
AssertionError: 26 not less than or equal to 25 : name too long: primary-0.68-gtk3-f378097e

----------------------------------------------------------------------
Ran 570 tests in 42.417s

FAILED (failures=3, errors=35, skipped=12, expected failures=24)
```
