### ISSUE TITLE
Error when opening Find dialog

### ISSUE THREAD

**Issue by cheese** [jaap-karssenberg/zim-desktop-wiki#68]
git f32807de355fa4c931936ebf6e5924546e9e6650

On Fedora 24

output of 'zim -D --standalone':
...
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
INFO: Open page: 计算机:常用命令 (计算机:常用命令)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: show_find
ERROR: Exception during action: show_find
Traceback (most recent call last):
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/actions.py", line 149, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/actions.py", line 132, in func
    self.func(instance, *args, **kwargs)
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 6280, in show_find
    self.find_bar.show()
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 6987, in show
    self.on_highlight_toggled()
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 6911, in on_highlight_toggled
    buffer.finder.set_highlight(highlight)
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 3330, in set_highlight
    self._update_highlight()
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 3343, in _update_highlight
    for start, end, _ in self._check_range(0, lastline, 1):
  File "/run/media/cheese/cheesenotes/zim-desktop-wiki/zim/gui/pageview.py", line 3352, in _check_range
    assert self.regex
AssertionError
DEBUG: Running ErrorDialog

**Comment by jaap-karssenberg** [comment]
Works fine here, any particular steps how to reproduce?

**Comment by cheese** [comment]
Restarting zim just recovered the issue. I don't know how to reproduce.

**Comment by jaap-karssenberg** [comment]
Closing this issue for now. Please re-open if seen again for the to be released zim 0.70 or newer
