### ISSUE TITLE
crashed when pasting a large log text into a newly created page

### ISSUE THREAD

**Issue by cheese** [jaap-karssenberg/zim-desktop-wiki#8]
zim 0.66 on Fedora 24.

widgets.py:2004:update_completion:AttributeError: 'NoneType' object has no attribute 'get_model'

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zim/signals.py", line 414, in callback
    self.cb_func(*arg, **kwarg)
  File "/usr/lib/python2.7/site-packages/zim/gui/widgets.py", line 2004, in update_completion
    model = self.get_completion().get_model()
AttributeError: 'NoneType' object has no attribute 'get_model'

Local variables in innermost frame:
text: ''
self: <PageEntry object at 0x7faa182453c0 (zim+gui+widgets+InputEntry at 0x55e1a4a93b60)>

**Comment by jaap-karssenberg** [comment]
Can you be more specific on what action triggered this error ?

From the output it looks like you were editing an entry in a dialog, but the summary says you were pasting into a page?

**Comment by cheese** [comment]
I tried several times doing the pasting again, but the issue did not occur.

**Comment by Tralen** [comment]
I experienced a similar problem. When doing any editing in a very long page, Zim 0.66 often crashes.

**Comment by jaap-karssenberg** [comment]
@Tralen can you include the error log you got, plug a more detailed description what you were doing at the time of the crash? Would like to verify it is the same or not.  

Thanks,

Jaap

**Comment by cheese** [comment]
Also occur in 0.67 version

**Comment by jaap-karssenberg** [comment]
@cheese: please include the error log or more detailed instructions how to reproduce

**Comment by cheese** [comment]
The issue is not always reproducible as I said in the original report. I have to wait for the next occurrence and then paste the error log.

**Comment by cheese** [comment]
Just caught an occurrence. I am creating the first sub-page of a newly created page.

This is the released version 0.67 of zim.

```
DEBUG: Action: new_sub_page
DEBUG: Opening dialog "New Sub Page - Zim"
DEBUG: Dialog response OK
INFO: Loading template from: /usr/share/zim/templates/wiki/Default.txt
INFO: Open page: ??:7.0TODO (??:7.0TODO)
DEBUG: Saving page: ??:7.0TODO
DEBUG: Store page: ??:7.0TODO
DEBUG: Index file: /run/media/cheese/cheesenotes/Notes/??/7.0TODO.txt
DEBUG: Closed dialog "New Sub Page"
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/media/cheese/cheesenotes/Notes/??
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Store page in background: ??:7.0TODO
DEBUG: Index file: /run/media/cheese/cheesenotes/Notes/??/7.0TODO.txt
DEBUG: Store page in background: ??:7.0TODO
DEBUG: Index file: /run/media/cheese/cheesenotes/Notes/??/7.0TODO.txt
DEBUG: Action: new_sub_page
DEBUG: Opening dialog "New Sub Page - Zim"
DEBUG: Dialog response OK
INFO: Loading template from: /usr/share/zim/templates/wiki/Default.txt
INFO: Open page: ??:7.0TODO:ws-tools?? (??:7.0TODO:ws-tools??)
DEBUG: Saving page: ??:7.0TODO:ws-tools??
DEBUG: Store page: ??:7.0TODO:ws-tools??
DEBUG: Index file: /run/media/cheese/cheesenotes/Notes/??/7.0TODO/ws-tools??.txt
DEBUG: Closed dialog "New Sub Page"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/zim/signals.py", line 414, in callback
    self.cb_func(*arg, **kwarg)
  File "/usr/lib/python2.7/site-packages/zim/gui/widgets.py", line 2005, in update_completion
    model = self.get_completion().get_model()
AttributeError: 'NoneType' object has no attribute 'get_model'
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /run/media/cheese/cheesenotes/Notes/??
DEBUG: Index folder: /run/media/cheese/cheesenotes/Notes/??/7.0TODO
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Store page in background: ??:7.0TODO:ws-tools??
DEBUG: Index file: /run/media/cheese/cheesenotes/Notes/??/7.0TODO/ws-tools??.txt
```
