### ISSUE TITLE
OS X dependencies

### ISSUE THREAD

**Issue by jbshirk** [jaap-karssenberg/zim-desktop-wiki#99]
following these directions:
http://zim-wiki.org/install.html

```
$ brew install gtk-mac-integration
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:843:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:135:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:134:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:111:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:143:in `<main>'

```

**Comment by Osndok** [comment]
No zim code appears in that stack trace, please report your issue here:
* https://github.com/Homebrew/brew/issues/new
